### ISSUE TITLE
Bug in neon-gemm-kernel-benchmark.cc?

### ISSUE THREAD

**Issue by flyingforyou** [google/gemmlowp#133] opened 2018-04-01 22:20 UTC
When I try to compile following the guide, 
aarch64-linux-android-clang++ -mcpu=cortex-a55 -fPIE -static -O3 --std=c++11 neon-gemm-kernel-benchmark.cc -o bench -D__ARM_FEATURE_DOTPROD
it shows errors like below.
neon-gemm-kernel-benchmark.cc:2585:10: error: invalid operand for instruction
        "udot v8.4s, v2.16b, v0.b[0]\n"
         ^
<inline asm>:29:21: note: instantiated into assembly here
udot v8.4s, v2.16b, v0.b[0]
                    ^
neon-gemm-kernel-benchmark.cc:2586:10: error: invalid operand for instruction
        "udot v9.4s, v2.16b, v0.b[1]\n"
         ^
<inline asm>:30:21: note: instantiated into assembly here
udot v9.4s, v2.16b, v0.b[1]
                    ^
neon-gemm-kernel-benchmark.cc:2588:10: error: invalid operand for instruction
        "udot v10.4s, v2.16b, v0.b[2]\n"
....

So, I think below patch should be applied for fixing compile issue.

diff --git a/standalone/neon-gemm-kernel-benchmark.cc b/standalone/neon-gemm-kernel-benchmark.cc
index aabeac9..e62115d 100644
--- a/standalone/neon-gemm-kernel-benchmark.cc
+++ b/standalone/neon-gemm-kernel-benchmark.cc
@@ -2103,11 +2103,11 @@ struct NEON_64bit_GEMM_Uint8Operands_Uint32Accumulators_noexpand_A57 {
         //
         //
         //                               +--------+--------+--------+--------+
-        //                               |v0.b[0] |v1.b[0] |v2.b[0] |v3.b[0] |
+        //                               |v0.4b[0] |v1.4b[0] |v2.b[0] |v3.b[0] |
         //                          Rhs  +--------+--------+--------+--------+
         //                               |  ...   |  ...   |  ...   |  ...   |
         //                               +--------+--------+--------+--------|
-        //                               |v0.b[15]|v1.b[15]|v2.b[15]|v3.b[15]|
+        //                               |v0.4b[15]|v1.4b[15]|v2.b[15]|v3.b[15]|
         //                               +--------+--------+--------+--------+
         //
         //                               |        |        |        |        |
@@ -2344,11 +2344,11 @@ struct NEON_64bit_GEMM_Int8Operands_AccumTwoWithin16Bits {
         // Register layout (ignoring the v8--v15 temporary 16bit accumulators):
         //
         //                               +--------+--------+--------+--------+
-        //                               |v0.b[0] |v1.b[0] |v2.b[0] |v3.b[0] |
+        //                               |v0.4b[0] |v1.4b[0] |v2.b[0] |v3.b[0] |
         //                          Rhs  +--------+--------+--------+--------+
         //                               |  ...   |  ...   |  ...   |  ...   |
         //                               +--------+--------+--------+--------|
-        //                               |v0.b[15]|v1.b[15]|v2.b[15]|v3.b[15]|
+        //                               |v0.4b[15]|v1.4b[15]|v2.b[15]|v3.b[15]|
         //                               +--------+--------+--------+--------+
         //
         //                               |        |        |        |        |
@@ -3197,41 +3197,41 @@ struct NEON_64bit_GEMM_Uint8Operands_Uint32Accumulators_dotproduct {
 
         // Start the MACs at the head of the loop - 1st cell from each side
         // already loaded.
-        "udot v8.4s, v2.16b, v0.b[0]\n"
-        "udot v9.4s, v2.16b, v0.b[1]\n"
+        "udot v8.4s, v2.16b, v0.4b[0]\n"
+        "udot v9.4s, v2.16b, v0.4b[1]\n"
         "ld1 {v1.16b}, [%[rhs_ptr]], #16\n"  // Load second Rhs cell.
-        "udot v10.4s, v2.16b, v0.b[2]\n"
-        "udot v11.4s, v2.16b, v0.b[3]\n"
+        "udot v10.4s, v2.16b, v0.4b[2]\n"
+        "udot v11.4s, v2.16b, v0.4b[3]\n"
         "ld1 {v3.16b}, [%[lhs_ptr]], #16\n"  // Load second Lhs cell.
-        "udot v12.4s, v2.16b, v1.b[0]\n"
-        "udot v13.4s, v2.16b, v1.b[1]\n"
+        "udot v12.4s, v2.16b, v1.4b[0]\n"
+        "udot v13.4s, v2.16b, v1.4b[1]\n"
         "ld1 {v4.16b}, [%[lhs_ptr]], #16\n"  // Load third Lhs cell.
-        "udot v14.4s, v2.16b, v1.b[2]\n"
-        "udot v15.4s, v2.16b, v1.b[3]\n"
+        "udot v14.4s, v2.16b, v1.4b[2]\n"
+        "udot v15.4s, v2.16b, v1.4b[3]\n"
         "ld1 {v2.16b}, [%[lhs_ptr]], #16\n"  // Done with first Lhs cell - load
         // for the next iteration early.
-        "udot v16.4s, v3.16b, v0.b[0]\n"
-        "udot v17.4s, v3.16b, v0.b[1]\n"
-        "udot v18.4s, v3.16b, v0.b[2]\n"
-        "udot v19.4s, v3.16b, v0.b[3]\n"
-        "udot v20.4s, v3.16b, v1.b[0]\n"
-        "udot v21.4s, v3.16b, v1.b[1]\n"
-        "udot v22.4s, v3.16b, v1.b[2]\n"
-        "udot v23.4s, v3.16b, v1.b[3]\n"
-        "udot v24.4s, v4.16b, v0.b[0]\n"
-        "udot v25.4s, v4.16b, v0.b[1]\n"
-        "udot v26.4s, v4.16b, v0.b[2]\n"
-        "udot v27.4s, v4.16b, v0.b[3]\n"
+        "udot v16.4s, v3.16b, v0.4b[0]\n"
+        "udot v17.4s, v3.16b, v0.4b[1]\n"
+        "udot v18.4s, v3.16b, v0.4b[2]\n"
+        "udot v19.4s, v3.16b, v0.4b[3]\n"
+        "udot v20.4s, v3.16b, v1.4b[0]\n"
+        "udot v21.4s, v3.16b, v1.4b[1]\n"
+        "udot v22.4s, v3.16b, v1.4b[2]\n"
+        "udot v23.4s, v3.16b, v1.4b[3]\n"
+        "udot v24.4s, v4.16b, v0.4b[0]\n"
+        "udot v25.4s, v4.16b, v0.4b[1]\n"
+        "udot v26.4s, v4.16b, v0.4b[2]\n"
+        "udot v27.4s, v4.16b, v0.4b[3]\n"
         "ld1 {v0.16b}, [%[rhs_ptr]], #16\n"  // Done with the first Rhs cell -
         // load for the next iteration early.
-        "udot v28.4s, v4.16b, v1.b[0]\n"
-        "udot v29.4s, v4.16b, v1.b[1]\n"
+        "udot v28.4s, v4.16b, v1.4b[0]\n"
+        "udot v29.4s, v4.16b, v1.4b[1]\n"
 
         // Loop.  Decrement loop index (depth) by 4 as udot processes 4
         // depth values.
         "subs %w[depth], %w[depth], #4\n"
-        "udot v30.4s, v4.16b, v1.b[2]\n"
-        "udot v31.4s, v4.16b, v1.b[3]\n"
+        "udot v30.4s, v4.16b, v1.4b[2]\n"
+        "udot v31.4s, v4.16b, v1.4b[3]\n"
 
         "bne " GEMMLOWP_LABEL_LOOP
         "b\n"
@@ -3327,53 +3327,53 @@ struct NEON_64bit_GEMM_Uint8Operands_Uint32Accumulators_dotproduct_A55r1 {
         GEMMLOWP_LABEL_LOOP
         ":\n"
 
-        "udot v8.4s, v2.16b, v0.b[0]\n"
+        "udot v8.4s, v2.16b, v0.4b[0]\n"
         "ldr d1, [%[rhs_ptr], #16]\n"         // Bottom half of v1
-        "udot v9.4s, v2.16b, v0.b[1]\n"
+        "udot v9.4s, v2.16b, v0.4b[1]\n"
         "ins v0.d[1], x18\n"                  // Finish loading v0
-        "udot v16.4s, v3.16b, v0.b[0]\n"      // out of sequence - used to reduce load/use pressure.
+        "udot v16.4s, v3.16b, v0.4b[0]\n"      // out of sequence - used to reduce load/use pressure.
         "ldr x18, [%[rhs_ptr], #24]\n"        // Top half of v1 to X register
-        "udot v17.4s, v3.16b, v0.b[1]\n"      // out of sequence - used to reduce load/use pressure.
+        "udot v17.4s, v3.16b, v0.4b[1]\n"      // out of sequence - used to reduce load/use pressure.
         "add %[rhs_ptr], %[rhs_ptr], #32\n"   // RHS loads complete - increment pointer.
-        "udot v10.4s, v2.16b, v0.b[2]\n"
+        "udot v10.4s, v2.16b, v0.4b[2]\n"
         "ldr d4, [%[lhs_ptr], #32]\n"         // Bottom half of v4
-        "udot v11.4s, v2.16b, v0.b[3]\n"
+        "udot v11.4s, v2.16b, v0.4b[3]\n"
         "ins v1.d[1], x18\n"                  // Finish loading v1
-        "udot v12.4s, v2.16b, v1.b[0]\n"
+        "udot v12.4s, v2.16b, v1.4b[0]\n"
         "ldr x18, [%[lhs_ptr], #40]\n"        // Top half of v4 to X register
-        "udot v13.4s, v2.16b, v1.b[1]\n"
+        "udot v13.4s, v2.16b, v1.4b[1]\n"
         "add %[lhs_ptr], %[lhs_ptr], #48\n"   // LHS loads complete - increment pointer.
-        "udot v14.4s, v2.16b, v1.b[2]\n"
+        "udot v14.4s, v2.16b, v1.4b[2]\n"
 
-        "udot v15.4s, v2.16b, v1.b[3]\n"
+        "udot v15.4s, v2.16b, v1.4b[3]\n"
         "ldr d2, [%[lhs_ptr]]\n"              // Bottom half of v2 (for next time)
-        "udot v18.4s, v3.16b, v0.b[2]\n"
+        "udot v18.4s, v3.16b, v0.4b[2]\n"
         "ins v4.d[1], x18\n"                  // Finish loading v4
-        "udot v19.4s, v3.16b, v0.b[3]\n"
+        "udot v19.4s, v3.16b, v0.4b[3]\n"
         "ldr x18, [%[lhs_ptr], #8]\n"         // Top half of next v2 to X register
-        "udot v20.4s, v3.16b, v1.b[0]\n"
+        "udot v20.4s, v3.16b, v1.4b[0]\n"
         "subs %w[depth], %w[depth], #4\n"
-        "udot v21.4s, v3.16b, v1.b[1]\n"
+        "udot v21.4s, v3.16b, v1.4b[1]\n"
 
-        "udot v22.4s, v3.16b, v1.b[2]\n"
+        "udot v22.4s, v3.16b, v1.4b[2]\n"
 
-        "udot v23.4s, v3.16b, v1.b[3]\n"
+        "udot v23.4s, v3.16b, v1.4b[3]\n"
         "ldr d3, [%[lhs_ptr], #16]\n"         // Bottom half of v3 (for next time)
-        "udot v24.4s, v4.16b, v0.b[0]\n"
+        "udot v24.4s, v4.16b, v0.4b[0]\n"
         "ins v2.d[1], x18\n"                  // Finish loading next v2
-        "udot v25.4s, v4.16b, v0.b[1]\n"
+        "udot v25.4s, v4.16b, v0.4b[1]\n"
         "ldr x18, [%[lhs_ptr], #24]\n"        // Top half of next v3 to X register
-        "udot v26.4s, v4.16b, v0.b[2]\n"
+        "udot v26.4s, v4.16b, v0.4b[2]\n"
 
-        "udot v27.4s, v4.16b, v0.b[3]\n"
+        "udot v27.4s, v4.16b, v0.4b[3]\n"
         "ldr d0, [%[rhs_ptr]]\n"              // Bottom half of v0 (for next time)
-        "udot v28.4s, v4.16b, v1.b[0]\n"
+        "udot v28.4s, v4.16b, v1.4b[0]\n"
         "ins v3.d[1], x18\n"                  // Finish loading next v3
-        "udot v29.4s, v4.16b, v1.b[1]\n"
+        "udot v29.4s, v4.16b, v1.4b[1]\n"
         "ldr x18, [%[rhs_ptr], #8]\n"         // Top half of next v0 to X register
-        "udot v30.4s, v4.16b, v1.b[2]\n"
+        "udot v30.4s, v4.16b, v1.4b[2]\n"
 
-        "udot v31.4s, v4.16b, v1.b[3]\n"
+        "udot v31.4s, v4.16b, v1.4b[3]\n"
         "bne " GEMMLOWP_LABEL_LOOP "b\n"

**Comment by bjacob** [comment] 2018-04-10 19:17
Don't pass -D__ARM_FEATURE_DOTPROD on the command line. __ARM_FEATURE_DOTPROD is not meant to be defined by the user. It's defined by the compiler itself when that instruction set extension is enabled. To enable it, pass a -march= flag with +dotprod in it. See https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

**Comment by flyingforyou** [comment] 2018-04-10 22:32
Hi bjacob.
I don't think "__ARM_FEATURE_DOTPROD" is supported in clang. Why did you mention about GCC's onlinedocs?

/*
 Build and run this benchmark on Android/ARM/32bit:
 ~/android/toolchains/arm-linux-androideabi/bin/arm-linux-androideabi-clang++ \
 -fPIE -pie -O3 --std=c++11 standalone/neon-gemm-kernel-benchmark.cc -o \
 /tmp/benchmark -mfloat-abi=softfp -mfpu=neon-vfpv4 && adb push /tmp/benchmark \
 /data/local/tmp && adb shell /data/local/tmp/benchmark
 Build and run this benchmark on Android/ARM/64bit:
 ~/android/toolchains/aarch64-linux-android/bin/**aarch64-linux-android-clang++ \**
 -fPIE -static -O3 --std=c++11 standalone/neon-gemm-kernel-benchmark.cc -o \
 /tmp/benchmark && adb push /tmp/benchmark /data/local/tmp && adb shell \
 /data/local/tmp/benchmark
 */

The build guide in "neon-gemm-kernel-benchmark.cc" uses clang not gcc. So, could you open this issue 
 again and think about how to fix this issue for clang please?

**Comment by bjacob** [comment] 2018-04-11 14:09
neon-gemm-kernel-benchmark.cc only happens to give an example command line with clang; it supports GCC just as well.

This issue is unrelated to Clang-vs-GCC.

The problem is that in your original command line above,

aarch64-linux-android-clang++ -mcpu=cortex-a55 -fPIE -static -O3 --std=c++11 neon-gemm-kernel-benchmark.cc -o bench -D__ARM_FEATURE_DOTPROD

you are manually definining __ARM_FEATURE_DOTPROD.

No one should ever do that.

Because this command line contains -D__ARM_FEATURE_DOTPROD , it is incorrect. That is why the only thing I can do with this issue, is to close it.

As explained in my previous comment, instead of manually defining __ARM_FEATURE_DOTPROD, you need to find out how to enabe this dotprod instruction set extension in your compiler. In my previous comment, I found some GCC documentation. Because GCC and Clang share mostly the same command-line flags, it is often the case that GCC and Clang documentation on such topics is interchangeable. If not, you're welcome to do more searching for the correct clang flags.

**Comment by flyingforyou** [comment] 2018-04-11 22:08
Hi bjacob.
I am pretty sure that Clang doesn't support to define "__ARM_FEATURE_DOTPROD" automatically.
I will touch you later when Clang can make that definition.

**Comment by bjacob** [comment] 2018-10-16 15:09
I'm sorry I didn't properly address your issue then and would like to right this now.

There were two separate issues here.
One issue is that, as you note above, Clang fails to define __ARM_FEATURE_DOTPROD when it should.  This is a Clang bug that affects Clang up to version 7 at least.  Googling, it seems that it's on its way to be fixed in Clang 8.  Until then, as you correctly noted above and I failed to understand, we do need to pass -D__ARM_FEATURE_DOTPROD to it.

The other issue is what you reported originally here: the syntax for this asm code was actually wrong, which is what clang rightly complained in your error messages,

```
neon-gemm-kernel-benchmark.cc:2585:10: error: invalid operand for instruction
"udot v8.4s, v2.16b, v0.b[0]\n"
```

This has been fixed in this commit,
https://github.com/google/gemmlowp/commit/2c33e3398097f67d31ad79329687191dd8861920

however as you can see this commit also makes a deeper change:  in order to more easily build on current toolchains that don't support udot instructions, it actually rewrites them in machine code. In this way, we now support even Clang 6.

Thanks and sorry again.

**Closed by bjacob** 2018-10-16 15:09 UTC
